import { CustomError } from "./CustomError";

export class NotFoundError extends CustomError{
    constructor(message = "Sua tarefa n√£o pode ser encontrada.") {
        super(message, 404);
    }
} 